name: deploy-to-server
on: [ push ]
jobs:
  check-bats-version:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: make blog-maker executable
        run: chmod +x ./blog-maker
      - name: run blog-maker to generate server site
        run: ./blog-maker -o ../blog
      - name: deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          ARGS: "-rltDvP --chmod=Dugo=rx,Fugo=r --delete"
          SOURCE: ../blog
          TARGET: ~/app/nginx/resource/
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
